sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hmj8YSyiCQRxarBkYA3hjxS9UC47OhZLwCoqXeMx6vME+kKfX5va4Qh1+R/7sfhcmhMuS5cPA73MargofbR2a1m1MpBnEWhB3hgBNkmwKCjMq47BIHLSpbeC7XIRGQypL+i1MfFe8e/pBKuD8xAA1+zo2mJoVIfPh7h2R2tQ5BuMu0fiO/8l7oH8yzotSHUxkibt7FC35J7RsjeFLq1LKXnCZ49QYDBTpWMu7S9CL9atzbO3dl6jclvuldrMCrdUALA4sk2TB/E3m5zwDTozN96RqqGMhReud5umtyTjgELQFs039eNiBIo9P5N+clZW9zLpUbLJnhPM/WxC0ddE9+IWCnmsRm2gnuoluJvZv0LdBYOMEkcU4pxyINI/Sv37ZD/jLdkrase5i3ZNeJ44rjDYTiT+zKmw2+Q3CIn8JmmFfNHa3VKv6BaYbK8OpGzVn4yeU42vRTXwMVnXed7xbjce+lWBg9qKQUx6Oi1oP/AE+3mdkjUhueIp4GEl6PuaBDiwK6f0PyAV9mka//ltPDD6B+tXJld70xBMa3FyFG7z7dlhRzIauGIWP0Izsb4fooykOyANCEcf1ULs+VAo15aO0vSIEfgoK2uC4++F5wXA0idkXVNDJEpYduYkevbJ1xldduW6y+eqgMNczbm0hgxhWbeKjG+SHN+kkAPyz+Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Song-Celestial--Or-Bhagavad-G-t---from-the-Mah-bh-rata---13-Being-a-discourse-between-Arju__2388
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy